#!/usr/bin/env bash
#
# Prepare a local development database for the OneTap POS desktop app.
#
# Idempotent: safe to run repeatedly. Creates a gitignored .env pointing at a
# local SQLite file, applies all Prisma migrations, and seeds a minimal but
# fully usable dataset (admin + waiter + cashier, menu, floor with tables).
#
# The Electron host and Prisma CLI both read DATABASE_URL from this .env.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

if [ ! -f .env ]; then
  cat > .env <<EOF
# Local development configuration (generated by .cursor/setup-dev-db.sh).
# Gitignored — safe to edit or delete; re-running the setup recreates it.
DATABASE_URL="file:$REPO_DIR/prisma/dev.db"
POS_ALLOW_LAN=true
ENABLE_ADMIN=true
POS_LICENSE_BYPASS=1
EOF
  echo "[setup-dev-db] wrote .env"
else
  echo "[setup-dev-db] .env already present, leaving it untouched"
fi

# Load .env so the Prisma CLI and seed script see DATABASE_URL.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

echo "[setup-dev-db] applying migrations…"
pnpm exec prisma migrate deploy

echo "[setup-dev-db] seeding…"
pnpm db:seed

echo "[setup-dev-db] done"
