-- Add more restaurant staff roles to the Role enum.
-- Safe to re-run: Postgres 16 supports IF NOT EXISTS for enum values.

ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'KP';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CHEF';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HEAD_CHEF';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FOOD_RUNNER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HOST';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BUSSER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BARTENDER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BARBACK';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CLEANER';

